apiVersion: apps/v1
kind: Deployment
metadata:
  name: net6api-dev
  namespace: testk8s
  labels:
    app: net6api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net6api
  template:
    metadata:
      labels:
        app: net6api
    spec:
      containers:
      - name: net6api
        image: hcobian/test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests: 
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 500Mi
            cpu: 0.5