apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: testk8s
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k8s/data"