apiVersion: v1
kind: Service
metadata:
  name: net6api-dev-app
  namespace: testk8s
spec:
  type: LoadBalancer
  selector:
    app: net6api
  ports:
  - name: http
    port: 8080
    targetPort: 80
  - name: https
    port: 8081
    targetPort: 443
